src/Makefile.am
src/e_uadk.c
src/uadk.h
src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_digest.c

openssl speed -engine uadk -async_jobs 1 -evp md5
openssl speed -engine uadk -async_jobs 1 -evp aes-128-cbc

openssl-uadk: add async mode

---

src/uadk_cipher.c

Still not find xts test case.
cbc and ctr need para -nopad in decode
openssl enc -aes-128-cbc -a -in data -out data.en -pass pass:123456  -K abc -iv abc -engine uadk -p
openssl enc -aes-128-cbc -a -d -in data.en -out data.de -pass pass:123456  -K abc -iv abc -engine uadk -p -nopad
openssl enc -aes-192-cbc -a -in data -out data.en -pass pass:123456  -K abc -iv abc -engine uadk -p
openssl enc -aes-192-cbc -a -d -in data.en -out data.de -pass pass:123456  -K abc -iv abc -engine uadk -p -nopad
openssl enc -aes-256-cbc -a -in data -out data.en -pass pass:123456  -K abc -iv abc -engine uadk -p
openssl enc -aes-256-cbc -a -d -in data.en -out data.de -pass pass:123456  -K abc -iv abc -engine uadk -p -nopad
openssl enc -aes-128-ecb -a -in data -out data.en -pass pass:123456  -K abc -iv abc -engine …

cipher: support ecb, ctr

---

src/e_uadk.c
src/uadk.h
src/uadk_rsa.c

test command:
openssl speed -elapsed -engine uadk -async_jobs 36 rsa2048

openssl-uadk:add rsa async mode

---

INSTALL.md

Initial version of INSTALL.md.
INSTALL.md  can be replaced by existing README.md file.

Initial version:Building and Installing guide of OpenSSL UADK engine

---

src/e_uadk.c
src/uadk.h
src/uadk_async.c
src/uadk_rsa.c

/usr/local/ssl/openssl.cnf
default_algorithms = RSA, DSA, RAND
async:
conf/nginx.conf
http {
ssl_async  on;
}

ras: work with nginx via both async and sync mode

---

src/uadk_ecc.c

It will cause segment fualt if calling uadk_ecc_uninit two times.
Signed-off-by: Hui Tang <tanghui20@huawei.com>

sm2: fix segment fualt

---

src/e_uadk.c

Check accelerators on platform, then register/unregister accordingly

e_uadk: add algorithm according to existing accelerators

---

test/sanity_test.sh

Add sanity test for openssl-uadk
Submitting new patch requires passing sanity_test.sh

uadk: add sanity test

---

INSTALL.md
src/uadk_cipher.c
test/sanity_test.sh

1.add sm4 and des3
2.fix alloc session problem

cipher add sm4 and des3

---

test/sanity_test.sh

Different platforms may have different accelerators,
Test only if the algorithm exists

sanity_test: test only if the algorithm exists

---

src/uadk_digest.c

sha256   6744.15k 30155.47k 109594.20k 322138.11k  739224.23k  815158.61k
sha512   7194.80k 30850.03k 113432.15k 363413.50k 1010953.08k 1152876.54k
sm3      7969.63k 30706.47k 111963.27k 326365.87k  742727.68k  817244.84k

digest: malloc data buffer for better performance

---

src/uadk_digest.c

1、add SHA384
2、Add digest soft work for breaking process.

uadk: digest - add SHA384 and soft work

---

src/uadk_cipher.c

Move set_key to uadk_cipher_init which only runs once in on session

cipher: move set_key to uadk_cipher_init

---

src/uadk_cipher.c

1. cipher: add new algs for Kunpeng 930
2. fix some coding style

cipher: add new algs for Kunpeng 930 

---

src/e_uadk.c
src/uadk.h
src/uadk_cipher.c

Platform 920 and 930 support different algorithms.
Rigister algorithm according to platform.

cipher: distinguish platform 920 and 930

---

README

Fix https://github.com/Linaro/openssl-uadk/issues/46

Readme: fix spelling error sgined.txt to signed.txt

---

src/e_uadk.c
src/uadk.h
src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_dh.c
src/uadk_digest.c
src/uadk_ec.c
src/uadk_pkey.c
src/uadk_pkey.h
src/uadk_rsa.c
src/uadk_sm2.c

Add missing copyright information.
Signed-off-by: Yang Shen <shenyang39@huawei.com>

engine: add copyright information

---

src/uadk_cipher.c

Optimize the 50 lines of warning.

cipher: optimize the process of private ctx setting

---

src/e_uadk.c
src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_dh.c
src/uadk_digest.c
src/uadk_ec.c
src/uadk_ecx.c
src/uadk_pkey.c
src/uadk_pkey.h
src/uadk_rsa.c
src/uadk_sm2.c

Contain a series of patches about cleanup and bugfix.

engine:  some cleanup and bugfix

---

src/e_uadk.c
src/uadk.h
src/uadk_async.c
src/uadk_dh.c
src/uadk_digest.c
src/uadk_ec.c
src/uadk_ecx.c
src/uadk_pkey.c
src/uadk_pkey.h
src/uadk_rsa.c
src/uadk_sm2.c

Contain：
cleanup ecc code and fix uadk engine compatibility issue.

engine: some cleanup 

---

src/uadk_cipher.c

Due to need to add the schedule for cipher, cipher session
initialzation not should be put before the ctx initial. so modify
the code.
Signed-off-by: Longfang Liu <liulongfang@huawei.com>

cipher: modify the process of cipher initialize

---

src/Makefile.am

First uadk engine version is 1.0.0

version: update to 1.0.0

---

src/uadk_digest.c

Support digest multiple updating by using the SEC stream mode.

digest: support digest multiple update

---

src/uadk_ec.c
src/uadk_pkey.c
src/uadk_rsa.c

Some cleanup about  RSA and ECC.

RSA  ECC cleanup

---

src/uadk_ec.c
src/uadk_sm2.c

This PR includes:
1. Bugfix about ecc init after allocating sess.
2. Cleanup sm2 compute digest function.

Cleanup of SM2 and Bugfix of ECC

---

src/uadk_rsa.c

Reduce parameter number of rsa_prime_mul_res(),
and add comments of BN_GENCB_call().

rsa: cleanup about prime generation

---

src/e_uadk.c

If hpre works in no-sva mode, and sec works in sva mode,
it will init hpre device first and return straightly, this
casuse sec not initialized correctly. So uadk engine should
init for both sva and no-sva device.

engine: fix engine can't work under hybrid mode

---

src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_dh.c
src/uadk_digest.c
src/uadk_pkey.c
src/uadk_rsa.c
src/uadk_sm2.c
src/v1/alg/pkey/hpre_rsa.c

Includes:
1. Fixup and cleanup about RSA.
2. Cleanup about ECC print log
3. Cleanup about KAE code.
4. Cleanup about some return value.

Fixup and cleanup aboout uadk engine

---

README

The new engine id name is 'uadk_engine'. So need to update
the README.

README: modify the engine id name

---

src/uadk_rsa.c

Includes:
1. Remove redundant judgment conditions.
2. Remove redundant function parameters.
3. Remove the redundant operation in soft RSA keygen method.
4. Use more efficient BN memory allocation method, and add
judgment of the results.

rsa: bugfix about redundant and inefficient operations

---

src/e_uadk.c
src/uadk.h
src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_dh.c
src/uadk_digest.c
src/uadk_pkey.c
src/uadk_rsa.c

1. Initialize resources only once.
2. Fix function type.
3. Fix RSA soft method.

 bugfix about uadk_engine async method and init function

---

docs/ReleaseNotes.md
docs/maintenance.md

ReleaseNotes.txt is required for each release.
Basically two releases each year, like in May and November.

docs: Add ReleaseNotes for release

---

src/uadk_cipher.c
src/uadk_rsa.c

This PR contains:
1. cipher: fix unused input parameter
2. rsa: fix wrong input parameters

uadk_engine: fixed some unused and wrong input parameters

---

src/uadk_cipher.c

Reduces some counting and branching judgments.

cipher: code clean for update iv and check length

---

configure.ac
docs/ReleaseNotes.md
src/Makefile.am

Release 1.2 in 2023.6
UAKD version is 2.5

uadk_engine: release 1.2

---

README.md
src/uadk_async.c
src/uadk_ecx.c
src/uadk_sm2.c
src/v1/alg/ciphers/sec_ciphers_soft.c
src/v1/alg/dh/hpre_dh_wd.c
src/v1/alg/pkey/hpre_rsa.c
src/v1/alg/pkey/hpre_rsa_utils.c
src/v1/async/async_task_queue.c
src/v1/utils/engine_log.c
src/v1/wdmngr/wd_alg_queue.c
src/v1/wdmngr/wd_queue_memory.c

openEuler requires setting PKG_CONFIG_PATH though /usr/local/lib/pkgconfig

readme: export PKG_CONFIG_PATH on openEuler

---

src/uadk_prov_digest.c

When provider default is not provided, priv->soft_md is NULL

uadk_prov_digest: provider default may not exist

---

src/uadk_digest.c

There is a problem caused by shared session that session status will be modified and another data flow will use the wrong status, so we need let each context get different session when we copy context, and the table is no longer needed.
Since the new session does not have any stream information, the engine need to send a message with total length and message status to uadk, so that uadk can correctly configure the session.

digest: alloc session and data when copy evp context

---

src/uadk_prov_cipher.c

Enable padding by default for block mode

uadk_prov_cipher: enable padding for block mode

---

src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_digest.c
src/uadk_sm2.c

* sm2 and digest add ctx allocation check
* cipher: cleanup repeated function invoking
* cleanup code style of async functions

uadk_engine: some bugfix and cleanup

---

src/uadk_rsa.c

evp interface will reuse the existing low level interface
Test:
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt \
rsa_keygen_bits:2048 -engine uadk_engine
openssl rsa -pubout -in private_key.pem -out public_key.pem \
-engine uadk_engine
openssl rsa -check -in private_key.pem
openssl dgst -sha256 -out data_hash.bin plaintext.txt openssl pkeyutl -encrypt -in data_hash.bin -out encrypted_hash.bin \
-pubin -inkey public_key.pem -engine uadk_engine
openssl pkeyutl -decrypt -in encrypted_hash.bin -out decrypted_hash.bin \
-inkey private_key.pem -engine uadk_engine
cmp decrypted_hash.bin data_hash.bin

rsa engine: add evp interface

---

src/uadk_aead.c
src/uadk_async.c
src/uadk_async.h
src/uadk_cipher.c
src/uadk_dh.c
src/uadk_digest.c
src/uadk_pkey.c
src/uadk_rsa.c

* fix the definition of async cb param
* fix for build warning
* fixed some issues related to aead

Incorporated some bugfixes.

---

src/uadk_digest.c

hw v2 does not support msg->in_bytes = 0, refer
drv/hisi_sec.c: digest_bd2_type_check
if (type == HASH_SINGLE_BLOCK) {
WD_ERR("hardware v2 not supports 0 size in block hash!\n");
return -WD_EINVAL;
}
But Nginx does send packets with in_bytes=0, sync mode is OK since it switches to sw, while async mode will fail.
Fixed by switching to sw for small packets in async mode too, Though only in_bytes=0 matters.

digest: async mode switch to sw for small packets

---

src/uadk_async.c

async_poll_process_func may stuck in sem_wait(&poll_queue.full_sem) when async_poll_task_free sem_destroy(&poll_queue.full_sem) causes Aborted (core dumped)
reproduce:
LD_PRELOAD=/usr/lib/libasan.so openssl engine uadk_engine -c -t
Fixed by wakeup async_poll_process_func and check exit flag

async: wakup async_poll_process_func before free async_poll_task_free

---

src/uadk_prov.h
src/uadk_prov_cipher.c
src/uadk_prov_init.c
test/sanity_test_provider.sh

SM2 is not supported on V2, should not be registered or tested

sanity_test: check SM2 exist or not
