src/Makefile.am, src/e_uadk.c, src/uadk.h, src/uadk_rsa.c
Fix:
1. uadk will install head files in /usr/local/include/uadk, so let use correct
head file, otherwise data will be wrong.
2. replace ctx to sess.
3. rename uadk_ras_sess.
4. fix ctx_mode bug.
5. introduce error print function.
6. add callback functions for genkey, enc, dec, sign, verify.
7. delete uadk_rsa_crypto(), use uadk_rsa_sync() instead.
8. clean uadk_rsa_fill_prikey(),add uadk_rsa_fill_prikey_crt().
9. rsa: remove init/destroy to e_uadk.c.
10. fix resource init & uninit.
11. remove no need macro.
12. make functions to static.
13. fix ENGINE_set_RSA() input.
14. add some missing functions.
15. add pubkey check function.
RSA functions:
So far, RSA-keygen,RSA-encrypt,RSA-decrypt,RSA-sign,RSA-verify SYNC MODE
functions are OK.
The test commands:
1. Generate RSA private key
openssl …
=> add RSA engine sync function

src/uadk_rsa.c
Currently ctx_num get from rsa_res_config.dev_num, which is
not correct if device is unbinded via
echo 0000:79:00.0 > /sys/bus/pci/drivers/hisi_hpre/unbind
Add checking device inside.
=> rsa: fix ctx_num if unbind device

src/uadk_rsa.c
This error comes from the wrong return value
of hpre_rsa_check_para(). It should return 1 when
parameters are valid and return 0 when invalid.
=> fix RSA verify failure.

INSTALL.md, src/Makefile.am, src/e_uadk.c, src/uadk.h, src/uadk_dh.c
Usage:
--generate shared secret key--
There are two users in this process.
-[step 1] Generate global public parameters, and save them in the file
dhparam.pem:
openssl dhparam -out dhparam.pem 2048
-[step 2] Generate own private key:
openssl genpkey -paramfile dhparam.pem -out privatekey1.pem
openssl genpkey -paramfile dhparam.pem -out privatekey2.pem
-[step 3] Generate public key:
openssl pkey -in privatekey1.pem -pubout -out publickey1.pem -engine uadk
openssl pkey -in privatekey2.pem -pubout -out publickey2.pem -engine uadk
-[step 4] After exchanging public key, each user can derive the shared secret:
openssl pkeyutl -derive -inkey privatekey1.pem -peerkey publickey2.pem -out
secret1.bin -engine uadk
openssl pkeyutl -derive -inkey privatekey2.pem -peerkey publickey1.pem -out
secret2.bin …
=> Support DH algorithm

INSTALL.md, src/Makefile.am, src/e_uadk.c, src/uadk.h, src/uadk_ec.c, src/uadk_pkey.c, src/uadk_pkey.h, src/uadk_sm2.c, test/sanity_test.sh
The summary is as follows:
1.Add uadk_ec.c to support ecdsa algorithm
2.Rename uadk_ecc.c to uadk_sm2.c
3.Move some public functions to uadk_pkey.[ch]
Signed-off-by: Hui Tang <tanghui20@huawei.com>
=> uadk_ec/uadk_ecc/uadk_pkey: support ecdsa algorithm

src/uadk_digest.c, test/sanity_test.sh
Supporting SHA224 for UADK engine.
=> uadk: digest - add SHA224

src/uadk_digest.c
soft_ctx is alloced but not free in digest_final
Move alloc and free soft_ctx only in uadk_digest_soft_work
=> digest: digest_final fix soft_ctx

src/uadk_digest.c
Modify the copy flag declaration. "1" is a magic number, use "bool"
instead of "int " maybe better.
=> digest: the copy flag use "bool" instead of "int"

src/uadk_cipher.c
priv_ctx like iv need to be updated after do_cipher
fix: https://github.com/Linaro/openssl-uadk/issues/52
=> cipher: update private contex

src/v1/alg/ciphers/sec_ciphers.c
sm4_ecb is not supported on Kunpeng920, removed in v1
=> cipher: v1 remove sm4_ecb support

README, src/uadk_cipher.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_pkey.c, src/uadk_rsa.c
The problem is the uadk will return error if the iv is zero in XTS mode. But this is a bug for XTS. So I think fix the parameters for XTS in one patch is better, and can wait to merge this pull request after uadk fix it.
=> Upstream for uadk engine

src/uadk_digest.c
Fix the sha384 testing failed.
=> digest: fix the sha384 testing failed

src/Makefile.am, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_pkey.h, test/sanity_test.sh
This PR contains:
1. Support X25519 and X448 algorithms, refer to uadk_ecx.c file
2. Replace the return value in uadk_cipher.c with macro, which is also used by other modules
3. Modify the makefile, add uadk_ecx.c file
=> Main support X25519 and X448 algs

src/uadk_ec.c, src/uadk_pkey.c, src/uadk_pkey.h, test/sanity_test.sh
This patch including:
1. support ECDH keygen and derive algs
2. support switching to openssl software methods
3. add test commands of ECDH
=> ecc: support ECDH algs

src/Makefile.am, src/e_uadk.c, test/sanity_test.sh
1. If no openssl.cnf like ci
openssl engine -c uadk /usr/local/lib/engines-1.1/libuadk_engine.so
2. If prividing /usr/local/ssl/openssl.cnf
The loading library can be specified in openssl.cnf by [engine_section]
Or dynamic_path in [uadk_section]
[engine_section]
// by default loading /usr/local/lib/engines-1.1/libuadk_engine.so
libuadk_engine = uadk_section
// by default loading /usr/local/lib/engines-1.1/uadk.so
uadk = uadk_section　　　　　
Or specified by:
[uadk_section]
dynamic_path = /usr/local/lib/engines-1.1/libuadk_engine.so
For example
/usr/local/ssl/openssl.cnf:
openssl_conf = openssl_def
[openssl_def]
engines = engine_section
[engine_section]
libuadk_engine = uadk_section
[uadk_section]
dynamic_path = /usr/local/lib/engines-1.1/libuadk_engine.so
default_algorithms = ALL …
=> uadk: rename library name libuadk_engine.so

README, src/e_uadk.c, src/uadk.h, src/uadk_cipher.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_ec.c, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_pkey.h, src/uadk_rsa.c
Through the environment variable function, users can configure the number of queue resources that can be applied by different algorithms by setting the algorithm switch in the openssl.cnf file.
=> Support environment variable for hpre/cipher/digest.

LICENSE
Add a license file because uadk_engine use an
Apache-2.0 license.
=> engine: Add license for uadk engine

src/uadk_cipher.c
The xts-aes need to setting the iv lens, it will cause the result of
software and hardware is non-consistent.
=> cipher: solving the problem of software and hardware non-consistent

src/uadk.h, src/uadk_cipher.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_ec.c, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_rsa.c, src/uadk_sm2.c
Due to the modification of the scheduler, the initialization of
environment variables needs to be adapted to the customizable scheduler.
Signed-off-by: Longfang Liu <liulongfang@huawei.com>
=> engine/sched: modify sched interface

src/uadk_digest.c
digest task not need to allocate session twice for one stream.
init->update->final as one stream.
=> digest: delete some duplicate code

src/e_uadk.c
This reverts commit ed37fc700d49f4940974d36c6bddf2af5e3d3cb7.
Fix build error:
e_uadk.c:244:12: warning: implicit declaration of function
=> Revert "engine: fix uadk engine compatibility issue"

src/uadk_ec.c, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_sm2.c
This patch includes:
1. Unified the return value form.
2. Remove redundant goto jumps.
=> ecc: cleanup the form of the return value

src/e_uadk.c, src/v1/uadk_v1.h, src/v1/wdmngr/wd_alg_queue.c, src/v1/wdmngr/wd_alg_queue.h
When uadk use no sva mode, it should use wd_get_available_dev_num,
otherwise, it will not find old kernel's device path with attrs.
=> engine: fix uadk engine compatibility issue

src/uadk_dh.c, src/uadk_pkey.c, src/uadk_sm2.c
When doing sm2_decrypt_check(), if the out param is NULL,
it is supposed to use sm2_plaintext_size() function to
get the output plain text length, rather than use
sm2_ciphertext_size().
=> ecc: bugfix about sm2 decryption

src/e_uadk.c, src/v1/uadk_v1.h
The original version of the kae engine supports the log system. So
need to be enabled the kae log feature at uadk_engine.
=> engine: add the kae log feature

src/uadk_rsa.c
The name of the function wd_rsa_key_bits()
has been changed to wd_rsa_get_key_bits()
in uadk driver, so it needs to be modified
in engine synchronously.
Signed-off-by: Junchong Pan <panjunchong@hisilicon.com>
=> rsa: fix interface name

src/uadk_cipher.c
if uadk_e_init_cipher failed, there is no need to
alloc cipher session, and alloc session will meet
a segmentation fault because sched_init is not
set by wd_cipher_init.
=> cipher: fix segmentation fault for uadk_e_ctx_init

src/uadk_cipher.c
Because sm4-ecb alg is deleted by mistake. So this alg
not be found in hardware V3.
=> cipher: sm4-ecb algorithm is deleted by mistake

src/e_uadk.c, src/uadk.h, src/uadk_async.c, src/uadk_async.h, src/uadk_cipher.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_ec.c, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_pkey.h, src/uadk_rsa.c, src/uadk_sm2.c
Change Copyright to 2022
Add Linaro Copyright as well
=> uadk-engine: change Copyright to 2022

src/e_uadk.c
String compare now use '==' while compare point and string,
changed to strcmp
Team:HISI_SW
Feature or Bugfix:Bugfix
Signed-off-by: JunchongPan <panjunchong@hisilicon.com>
=> uadk_engine:fix string compare mode

src/uadk_cipher.c
Optimize the process of ctx initialization as switching to soft work.
If the ctx resources of a thread are insufficient at the beginning, the
thread can't apply for resources again. Therefore, an flag checking is
required.
=> cipher: optimize the process of ctx initialization

src/uadk.h, src/uadk_cipher.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_pkey.c, src/uadk_rsa.c
Increase the count of packet receiving timeout as doing async
jobs. Prevents falling into an infinite loop.
=> engine: add receiving timeout count

src/uadk_utils.c
On x86 local build:
autoreconf -i
./configure --libdir=/usr/local/lib/engines-1.1/
make -j4
uadk_utils.c: In function ‘uadk_memcpy’:
uadk_utils.c:23:2: error: unknown register name ‘q1’ in ‘asm’
__asm__ __volatile__(
^
uadk_utils.c:23:2: error: unknown register name ‘q0’ in ‘asm’ uadk_utils.c:23:2: error: unknown register name ‘x14’ in ‘asm’ uadk_utils.c:23:2: error: unknown register name ‘x5’ in ‘asm’ uadk_utils.c:23:2: error: unknown register name ‘x4’ in ‘asm’ uadk_utils.c:23:2: error: unknown register name ‘x3’ in ‘asm’
With this patch, x86 build is OK
=> uadk_utils: fix x86 local build

src/e_uadk.c, src/uadk.h, src/uadk_async.c, src/uadk_async.h, src/uadk_cipher.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_ec.c, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_pkey.h, src/uadk_rsa.c, src/uadk_sm2.c, test/sanity_test.sh
Hao Fang (1):
uadk_engine: use HW_V2/HW_V3 to distinguish different hardware
platforms.
Longfang Liu (1):
uadk/engine: Update the numa parameter of the scheduler
Zhiqi Song (6):
sm2: bugfix about segfault in sm2 ctrl function
uadk_engine: bugfix side effects of right operand
uadk_engine: cleanup static check warning of clangtidy tool
uadk_engine: bugfix enable environment variable
uadk_engine: cleanup magic number and comments
uadk_engine: cleanup header file
=> Some bugfix and cleanup

Makefile.am, configure.ac, src/Makefile.am
Using pkg-config to get info of dependent library: libwd, libwd_crypto, libcrypto, which maybe installed to tmp folder.
Also check openssl:libcrypto version, only 1.1.x are supported.
For example uadk is installed to /tmp/build instead of /usr/local/lib
$ pkg-config libwd --libs
No package 'libwd' found
$ cd openssl-uadk
$ autoreconf
$ ./configure --prefix=/tmp/build
$ make
no library is generated.
$ export PKG_CONFIG_PATH=/tmp/build/lib/pkgconfig/ $ pkg-config libwd --libs
-L/tmp/build/lib -lwd
$ cd openssl-uadk
$ autoreconf
$ ./configure --prefix=/tmp/build
$ make
$ make install
$ ls /tmp/build/lib/uadk_engine.so
$ openssl engine -c /tmp/build/lib/uadk_engine.so
(/tmp/build/lib/uadk_engine.so) uadk hardware engine support Loaded: (uadk_engine) uadk hardware engine support
Signed-off-by: …
=> Makefile: Using pkg-config to check dependent lib

README.md, configure.ac, docs/maintenance.md
Repo's name has changed to uadk_engine, so modify accordingly.
=> uadk_engine: rename openssl-uadk to uadk_engine

src/Makefile.am
uadk_engine_la_cflags will override AM_CFLAGS,
so use uadk_engine_la_cflags to set DKAE flags.
=> Makefile: fix AM_CFLAGS not working for kae

configure.ac, docs/ReleaseNotes.md, src/Makefile.am
Release 1.1 in 2022.12
UAKD version is 2.4
=> uadk_engine: release 1.1

src/uadk_digest.c
If use the 'digest_copy' in task, like sm2 signature and verification, the private variable values may not be updated. This will cause the sm2 verify failure. So add the value cleanup in the 'digest init'.
=> digest: add private variable values initialization

src/v1/alg/dh/hpre_dh_wd.c
Fix implicit declaration of function ‘OPENSSL_calloc’ with calloc
=> v1: fix implicit declaration of function ‘OPENSSL_calloc’

src/uadk_cipher.c
cipher: fix double free error
When wd_cipher_set_key() failed, after the handle is released, the handle should be set to 0 to avoid reusing.
cipher: fix set key error
Initialize the algorithm type again to prevent the algorithm type from being changed.
cipher: fix async hardware computing error
If the length of the input data does not reach to hardware computing threshold, directly switch to soft cipher.
=> cipher: fix double free error, set key error and async hardware computing error

src/uadk_prov_cipher.c, src/uadk_prov_init.c
commit d88411ccccb4df249ba196860f3f1cba090398bd (HEAD -> working_provider_load, guodong/working_provider_load)
Author: Guodong Xu <guodong.xu@linaro.org>
Date:   Mon Sep 4 09:45:05 2023 +0800
uadk_provider: load default provider into Global library context
Implementations in default provider are required in some cases.
For example when the package size is small.
In current design, we load default provider into Global library context,
aka. NULL.
Signed-off-by: Guodong Xu <guodong.xu@linaro.org>
commit d637ad5c611435ed2ca3a4adfdb33e7a64d4b148
Author: Guodong Xu <guodong.xu@linaro.org>
Date:   Sun Sep 3 06:36:37 2023 +0800
uadk_provider: iv_len in SM4_ECB mode must be 0
iv_len of ECB mode must be 0. Without this, openssl's evp_test
will fail at:
[openssl.git]/test/evp_test.c, …
=> Working provider load and a bug fix for sm4-ecb

src/uadk_async.c, src/uadk_async.h, src/uadk_cipher.c, src/uadk_engine_init.c, src/uadk_prov_cipher.c, src/uadk_prov_init.c
Unlike openssl 1.1, openssl 3.0 requires "It is the responsibility of the cipher implementation to handle input lengths that are no multiples of the block length" [1]
Add padding handling via referring
providers/implementations/ciphers/ciphercommon.c
Additionally, the patch finds that using software and hardware ciphers does not work properly if alternating between the two. If using hardware, it is necessary to keep using hardware, and vice versa.
[1] https://www.openssl.org/docs/manmaster/man7/provider-cipher.html
=> uadk_prov_cipher: fix padding

src/Makefile.am, src/uadk_prov.h, src/uadk_prov_init.c, src/uadk_prov_rsa.c, test/sanity_test.sh
Test:
openssl speed -provider uadk_provider -provider default rsa1024 openssl speed -provider $engine_id -provider default rsa2048 openssl speed -provider $engine_id -provider default rsa4096 openssl speed -provider $engine_id -provider default -async_jobs 1 rsa1024 openssl speed -provider $engine_id -provider default -async_jobs 1 rsa2048 openssl speed -provider $engine_id -provider default -async_jobs 1 rsa4096
openssl genrsa -out prikey.pem -provider uadk_provider \
-provider default 1024
openssl rsa -in prikey.pem -pubout -out pubkey.pem \
-provider uadk_provider -provider default
echo "Content to be encrypted" > plain.txt
openssl rsautl -encrypt -in plain.txt -inkey pubkey.pem -pubin \
-out enc.txt -provider uadk_provider -provider default
openssl rsautl -decrypt -in enc.txt -inkey …
=> uadk: add uadk_prov_rsa for openssl 3.0

src/uadk_prov.h, src/uadk_prov_init.c
Use a more informative name uadk_xxx instead of p_xxx
=> uadk_prov_init: change name more informative

configure.ac, src/uadk_prov.h, src/uadk_prov_cipher.c, src/uadk_prov_digest.c, src/uadk_prov_init.c, uadk_provider.cnf
resolve configure warning
configure.ac:9: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
=> configure: use LT_INIT to replace obsolete AC_PROG_LIBTOOL

src/uadk.h, src/uadk_aead.c, src/uadk_async.c, src/uadk_async.h, src/uadk_cipher.c, src/uadk_cipher_adapter.c, src/uadk_dh.c, src/uadk_digest.c, src/uadk_ec.c, src/uadk_ecx.c, src/uadk_pkey.c, src/uadk_rsa.c, src/uadk_sm2.c, src/v1/alg/ciphers/sec_ciphers.c, src/v1/alg/pkey/hpre_rsa.c, src/v1/alg/pkey/hpre_wd.c
This patchset contains some bugfix and cleanup.
Hao Fang (6):
uadk_engine: cipher/digest: fixes for priv address check
uadk_engine: ec: add BN_new memory check
uadk_engine: rsa: fix mem leak for from_buf
uadk_engine: uadk_rsa: fix to free from_buffer
uadk_engine: uask_async: fix thread_attr res leak
uadk_engine: async: fix add async send timeout
Qi Tao (3):
cipher: uadk_e_bind_ciphers function is optimized
cipher: UADK_CIPHER_DESCR is optimized
uadk_engine/v1: fix g_sec_ciphers_info[] error
Weili Qian (2):
uadk_engine: add device initialization status
sm2: fixup switching soft sm2 decrypt problem
Zhiqi Song (6):
ecc: optimize sm2 sign check function
digest: fix the address of async op
uadk_engine: fixup resource management issues
ecc: add check of siglen
v1/pkey: add check of qlist …
=> uadk_engine: some bugfix and cleanup

src/uadk_cipher.c
The flags of sm4 cfb should be EVP_CIPH_CFB_MODE,
so fix it.
=> uadk_cipher: fixup sm4 cfb flags

src/v1/alg/dh/hpre_dh_wd.c
If iova_map and iova_unmap ops are not registered, wcrypto_create_dh_ctx() will return fail since parameters check fails.
=> v1/dh: add iova_map and iova_unmap ops

configure.ac, src/Makefile.am
Add PIE, PIC, BIND_NOW, SP, FS, NO Rpath/RunPath, Ftrapv and Strip compilation options.
=> uadk_engine: add secure compilation option

src/uadk_utils.c
autoreconf -i
./configure CC=clang
make -j8
reports error:
uadk_utils.c:53:33: error: unknown register name 'q0' in asm uadk_utils.c:53:39: error: unknown register name 'q1' in asm
Fix with "v0", "v1", instead of "q0", "q1"
=> uadk_util: fix clang build error

src/uadk_prov_cipher.c
Cipher can use same op for dec and enc, so alloc 1 op.
Otherwise, there maybe issue in env case, where
driver->op_type_num is used,
drv/hisi_sec.c:621:     .op_type_num = 1,
=> uadk_prov_cipher: dec and enc use same op

src/uadk_prov_dh.c, src/uadk_prov_rsa.c
KEYMGMT struct is different in 3.2 causes Segmentation fault. Fixed it by adding version check.
=> kmgmt: KEYMGMT struct is different in 3.2

src/uadk_digest.c, src/uadk_prov_cipher.c
By default, do_soft is disabled.
To enable sw handling, need set enable_sw_offload = 1 via OPENSSL_CONF
For example: uadk_provider.cnf
openssl_conf = openssl_init
[openssl_init]
providers = provider_sect
[provider_sect]
uadk_provider = uadk_sect
[uadk_sect]
activate = 1
enable_sw_offload = 1
export OPENSSL_CONF=uadk_provider.cnf
=> uadk_prov_cipher: do_soft when hw failed

src/uadk_cipher_adapter.c
v2 does not support aead, causing nginx failure.
log:
do aead update operation failed, ret: -22, state: 0!
nginx works now after removing aead parts.
=> cipher_adapter: remote aead in v2

src/uadk_rsa.c
refer v1, adding RSA_NO_PADDING and RSA_SSLV23_PADDING. otherwise nginx will fail
/usr/local/nginx/conf/nginx.conf
ssl_ciphers  ECDHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers  on;
Test:
ab -n 1 -c 1 https://localhost/
=> rsa: add RSA_NO_PADDING and RSA_SSLV23_PADDING

src/uadk_rsa.c
Add version check for RSA_SSLV23_PADDING to fix
build rsa engine error in OpenSSL 3.x
RSA_SSLV23_PADDING removed in OpenSSL 3.x
https://github.com/SWI-Prolog/packages-ssl/issues/160
=> rsa: add version check for RSA_SSLV23_PADDING

src/uadk_prov_dh.c, src/uadk_prov_rsa.c
Issue:
There are structural differences in the evp_keymgmt_st, evp_keyexch_st, and evp_asym_cipher_st structs between OpenSSL 3.2 and 3.0.
vimdiff 3.2/crypto/evp/evp_local.h 3.0/crypto/evp/evp_local.h
Solution:
Version Check:
Introduce a check for OPENSSL_VERSION_NUMBER at compile time.
Version-Specific Builds:
Based on the version, the uadk_provider will be built with the appropriate OpenSSL library to ensure compatibility with the struct definitions.
=> prov: EVP struct differences in OpenSSL 3.0

src/uadk_async.c
openssl engine -c uadk_engine
does not call uadk_init & uadk_finish, but call uadk_destroy, which call pthread_join(poll_queue.thread_id) but the thread_id is not initialized, causing segmentation fault in 2403.
Test: 2403
autoreconf -i
make clean
./configure --enable-engine --libdir=/usr/lib64/engines-3/ CFLAGS=-Wall make; make install
openssl engine -c uadk_engine
=> uadk_async: check thread_id before pthread_join

src/uadk_async.c, src/uadk_async.h
When a hardware error occurs, asynchronous receiving will reture an abnormal value. In this case, the corresponding sending thread cannot be sure to woken up. Therefore, the counting method is used to wake up the corresponding thread whose number of failures exceeds the threshold.
huangchenghai:
请教个问题，我们的异步模型采用的轮询方式对各个发包任务调用poll函数，如果成功收包会在回调函数中准确唤醒发包函数，但是如果由于各种原因导致收包失败，会将当前id的发包线程唤醒。此时会存在一种情况，uadk poll接口并不能提供那个线程的收包异常了，此时相当于任意唤醒一个发包线程以保证不会有业务阻塞的情况。如果错误唤醒发包线程继续走下去释放了req资源，那么后续poll接口又收到了该已经结束的线程的包，就会在回调函数中出现内存错误。所以我认为该异步模型应该有待进一步改进，以适配uadk poll模型。
当前我想到的规避式方式是采用计数方式，统计对应task的poll失败次数，当超过一定次阈值时才唤醒对应的id的发包线程。
=> uadk_provider: fix the async issue when receive fail
